language: node_js
node_js: 11
sudo: required
branches:
  only:
  - master
cache:
  directories:
    - node_modules    
addons:
  ssh_known_hosts:
  - 45.76.145.2
install:
 # - npm install -g gulp
    - npm install -g @vue/cli
    - npm install -g @vue/cli-service-global
    - npm install -g workbox-cli
    - npm install
before_script:
    sudo apt-get install sshpass
    #- git config --global user.name "birdsofsummer"
    #- git config --global user.email "kopor_oo@qq.com" 
script:
    - npm run build
after_script:
    - workbox generateSW workbox-config.js
    - cp static/index.html static/template.html
    - cp static/index.html static/admin.html
    - date >static/ttt
    - cat static/ttt
    - sshpass -e scp -r static root@45.76.145.2:/opt/jiakai/ 
    - ls 
    - echo done
      #- tar cvf static.star static
      #- git add --all .
      #- git commit --message "tt"
      #- git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" master:master
   #- sshpass -e ssh root@45.76.145.2 -o stricthostkeychecking=no "/opt/jiakai/vps.sh"
