language: node_js
node_js: 11
sudo: required
branches:
  only:
  - master
cache:
  directories:
    - node_modules    
addons:
  ssh_known_hosts:
  - 45.76.145.2
install:
 # - npm install -g gulp
    - npm install -g @vue/cli
    - npm install -g @vue/cli-service-global
    - npm install -g workbox-cli
    - npm install
before_script:
    - git config --global user.name "birdsofsummer"
    - git config --global user.email "kopor_oo@qq.com" 
script:
    - npm run build
after_script:
    - workbox generateSW workbox-config.js
    - cp static/index.html static/template.html
    - cp static/index.html static/admin.html
    - date >static/ttt
    - git add --all .
    - git commit --message "tt"
    - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" dist:dist
    - sshpass -e ssh root@45.76.145.2 -o stricthostkeychecking=no "/opt/jiakai/vps.sh"
    - cat static/ttt
    - echo done
